### ISSUE TITLE
In-depth explanations of the various model parameters in GS

### ISSUE THREAD

**Issue by thvasilo** [awslabs/graphstorm#1004]
Our run configuration docs are currently at a high level.

We should have more detailed documentation that explain the different models, loss functions etc. in a form of user guide with equations and paper links when possible.

**Comment by classicsong** [comment]
The models are listed in https://graphstorm.readthedocs.io/en/v0.3.1/api/references/index.html. 
However, the loss functions are not listed. We should add them.
