### ISSUE TITLE
Support in-library launch scripts for built-in model training and inference.

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#102]
## Motivation
To run a GraphStorm training task, a user need to take the following steps:
1. Pip install GraphStorm library
2. git clone https://github.com/dmlc/dgl.git
3. git clone https://github.com/awslabs/graphstorm.git
4. Use dgl launch.py script to launch a task.

The steps are to complex as the user needs to download may codebases to get the entrypoint scripts.

### Proposal
We will integrate launch.py as well as other entrypoint scripts provided in training_scripts/inference_scripts into GraphStorm library. Then the UX will be:
1. Pip install GraphStorm library
2. Run a training task using built-in training script: `python3 -m graphstorm.run.gsf_node_classification xxx` or `python3 -m graphstorm.run.gsf_link_prediction xxx`

For user defined training script: `python3 -m graphstorm.run.launch  xxx <PATH_TO_SCRIPT> xxx` .

**Comment by zhjwy9343** [comment]
Is this running within a container or not?

**Comment by classicsong** [comment]
It can run within a container.
