### ISSUE TITLE
Use relative paths in tutorials and examples

### ISSUE THREAD

**Issue by thvasilo** [awslabs/graphstorm#1027]
Our tutorials like https://graphstorm.readthedocs.io/en/v0.3.1/tutorials/quick-start.html are using absolute paths, assuming they are being executed from within the GS Docker container. 

When referring to files in the repository we should be using paths relative to the root repo directory, to improve UX and allow users to directly copy-paste code from the guides.

**Comment by zhjwy9343** [comment]
To reduce confusion for readers of our documentations, we will unify the path to all graphstorm's artifacts, e.g., example codes, nodebooks, and yaml/json files, to be `path_to_graphstorm/`, and add a line of command `cd path_to_graphstorm/` before any commands that refer to the relative path. 

And then, all commands will be relative to this path, e.g. the command 

`python3 /graphstorm/examples/acm_data.py \`,

will become,

 `python3 examples/acm_data.py \`.
