### ISSUE TITLE
Can I use gnn models from graphstorm in dgl-ke？

### ISSUE THREAD

**Issue by Diison** [awslabs/graphstorm#1095]
Now I'm using your great work dgl-ke: https://github.com/awslabs/dgl-ke to conduct some experiments. 
The speed of del-ke is impressive! But when I need to try gnn models, I realize there are no such implements.
Then I found graphstorm, so can I use gnn models from graphstorm in dgl-ke? If this is possible, it will save me a lot of time.
I would be very appreciative if you could give an example of how to use it.

**Comment by classicsong** [comment]
I will be very hard to do so.
I would suggest you to directly use GraphStorm. We have ported the distmult, transe and rotate from dgl-ke to GraphStorm.
