### ISSUE TITLE
[Feature Request] Users need to set the train/val/test by their own in graph construction

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#155]
Current graph construction configuration only allow users to set the split percentages. But users may want to preset the split by their own logics, e.g., timestamp. 

Need to allow users to setup their own train/val/test masks in both data files and the configuration JSON file.

**Comment by zheng-da** [comment]
This is a duplicated task.

https://github.com/awslabs/graphstorm/issues/41
