### ISSUE TITLE
Slow link prediction inference pipeline

### ISSUE THREAD

**Issue by isratnisa** [awslabs/graphstorm#169]
Current link prediction inference pipeline is very slow. A single epoch takes 45 minutes using a batch size of 1024 on ogbn-papers100M dataset on g4dn.metal instance. Our profiling results indicates that fetching node embeddings from remote machines is one of the key bottlenecks. The network utilization is very low.

**Comment by zheng-da** [comment]
there are multiple PRs related to this. Is this done?
