### ISSUE TITLE
[Feature request] Warning handling: Graph convolution returned empty dictionary for node with type: {}

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#189]
Currently this warning is printed all the times: 
`
print("Warning. Graph convolution returned empty dictionary, "
    f"for node with type: {str(k)}")
`
Can we print this only once and/or use `warnings.warn()` so it can be filtered by users?

**Comment by zheng-da** [comment]
This is fixed here. https://github.com/awslabs/graphstorm/pull/208
