### ISSUE TITLE
[Bug] Best epoch does not work

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#248]
- The best epoch output is always 0 in Edge classification/regression and Link Prediction.
- There is no best epoch output for Node classification/regression.

Without this indicator, it is hard to find the best epoch+iteration for the inference. Need to save logs and search for the best evaluation value back to find the best epoch+iteration.

**Comment by classicsong** [comment]
We have some 'Best Iteration' in our printing logs. Do you mean we need to save a meta-file indicating the best path to the best model?
