### ISSUE TITLE
Avoid keeping a distributed tensors for every intermediate GNN layer in the inference.

### ISSUE THREAD

**Issue by zheng-da** [awslabs/graphstorm#414]
The current code allocates a distributed tensor to store the embeddings in the intermediate layers. These embeddings are not removed after inference. We need to have an effective way of cleaning up the distributed tensors during the inference and after the  inference.

**Comment by classicsong** [comment]
I remember there is a bug when releasing DistTensor in dgl. The bug is related to shared memory.

**Comment by classicsong** [comment]
@zheng-da Have we solved this?
