### ISSUE TITLE
Running test training fails on Macbook Pro (intel)

### ISSUE THREAD

**Issue by Ishitori** [awslabs/graphstorm#499]
Hi team,

I have created a tiny graph and I want to run graphstorm locally on my Macbook Pro (intel processor) laptop to do link prediction. I don't have NVidia GPU, and I install dependencies using default pip commans (pyhon 3.11):

```
pip install graphstorm
pip install dgl
```

I use PyTorch as a backend (default, didn't change it. PyTorch version 2.0.1)

I have created DistDGL graph using provided tool, and trying to run training script. I opened ssh on my laptop and allowed to do password-less login, and it can login.

The problem starts when it tries to create a `server` via gsgnn_lp.py. It calls `rpc.reset()` at `dgl/distributed/dist_context.py, line 266` and fails with `NameError: name '_CAPI_DGLRPCReset' is not defined`. 

I think this suggests that I am missing a dependency, but I am not sure.
Could someone help me track it down, please?

Thank you.

**Comment by classicsong** [comment]
You can try to run GraphStorm in Standalone mode: https://github.com/awslabs/graphstorm/blob/74c99ec86b54c61d3184372c15e02e6efe761f2a/tests/end2end-tests/graphstorm-ec/test.sh#L30-L31

**Comment by Ishitori** [comment]
Well, if I use this line on main branch, I get `ImportError: cannot import name 'use_wholegraph' from 'graphstorm.utils' (/usr/local/lib/python3.11/site-packages/graphstorm/utils.py)`. But I don't think it is related...

I am also doing Link prediction, not classification or regression, so I guess I need to use `gsgnn_lp.py`, right? If so, I don't see how can I run it in standalone mode - it tries to initialize distributed context almost immedeately...

**Comment by classicsong** [comment]
Can you use the latest code?
WholeGraph support was recently added.

**Comment by Ishitori** [comment]
Thanks, I have updated the code and it looks like the problem is gone. Thank you!
