### ISSUE TITLE
Graph construction and nodes order

### ISSUE THREAD

**Issue by Ishitori** [awslabs/graphstorm#520]
When I call gconstruct, I try to AVOID remapping of the node ids, because my nodes are already mapped to intagers between 0 and N. But I have noticed that remapping still happens, because graphstorm's check if nodes are sequentially mapped from 0 to N expects nodes to be ordered (`graphstorm/gconstruct/construct_graph.py,329`):

```
 and np.all(type_node_id_map == np.arange(len(type_node_id_map))) \
```

My nodes are already mapped from 0 to N, but looks like they are not ordered once feeded into gconstruct. Thus, this check fails, and remapping of the nodes is called.

Now, I can fix it via changing this comparison by adding sorting:

```
and np.all(np.sort(type_node_id_map, kind='heapsort') == np.arange(len(type_node_id_map))) \
```

This results in True check, and remapping doesn't happen. But the question is: does graphstorm expects ordered list of nodes and/or edges when converting the data? I am feeding data from multiple parquet files produced by Spark, so if this is the requirement, I will sort it in Spark. Or is it a simple checking bug and the end result of the conversion doesn't really depend on a particular order of nodes?

Thank you.

**Comment by classicsong** [comment]
GraphStorm expects the ordered list of nodes. If the nodes are not sorted before-a-head, GraphStorm needs to sort the nodes and also shuffle the node features.
This is not required for edges.

**Comment by Ishitori** [comment]
Ok, got it. Will make sure to order nodes in Spark
