### ISSUE TITLE
Link Prediction's infer evaluated MRR is much larger than trainer evaluated MRR

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#57]
I tested with MAG data.

For MAG, the best trainer test MRR is around 0.38, but the infer test MRR is about 0.83.

No clue about why the test MRRs have such big difference.

**Comment by zhjwy9343** [comment]
After debugging, found the cause of the difference. It is the difference between the following two arguments.
    num_negative_edges: 4
    num_negative_edges_eval: 200

During training, the evaluator uses "num_negative_edges" for validation and testing. While inference, the evaluator use the "num_negative_edges_eval".

So for a large number of negative edges, the model performs much better.

**Comment by zheng-da** [comment]
is this problem fixed?

**Comment by classicsong** [comment]
The problem is fixed.
