### ISSUE TITLE
get node embedding after training ?

### ISSUE THREAD

**Issue by arita37** [awslabs/graphstorm#592]
How to get the node embedding vector after training ?
Thx

**Comment by classicsong** [comment]
We would recommend you to run graphstorm.run.gs_gen_node_embedding to generate node embeddings. You can refer to tests/end2end-tests/graphstorm-lp/mgpu_test.sh for an example.

**Comment by jalencato** [comment]
There is another example here, you can refer to it: https://graphstorm.readthedocs.io/en/latest/tutorials/quick-start.html#generating-embedding,
