### ISSUE TITLE
GraphStorm Trainer cannot output the logs

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#655]
Issue details:

When use GraphStorm Trainer API to program, Trainer classes cannot output training logs out because GraphStorm itself use TaskTracker to control the log output. In order to show logs, users need to setup_task_tracker in a Trainer class. However, in order to initialize a task_tracker, users need to create a GSConfig object, which is very hard and not a desired behavior.

In the Stand_along_notebook.ipynb file, the NodeTrainer has a `history` property that stores the training and evaluation metric value history. The notebook use this property to show the metrics. But this history does not include other valuable information such as training loss, which TaskTracker can output.

Potential solution:
1. keep the .history property untouched.
2. give GraphStorm Trainers’ a default TaskTracker.
3. Implement a default GS TaskTracker, and
4. Change GS AbsTaskTracker to remove the dependency on GSConfig.

**Comment by classicsong** [comment]
@zhjwy9343 Is this issued resolved with your PR?

**Comment by zhjwy9343** [comment]
Yes, my PR resolved this issue.
