### ISSUE TITLE
Cannot download OGB Datasets 

### ISSUE THREAD

**Issue by prateekdesai04** [awslabs/graphstorm#69]
Unable to download OGB datasets required for partitioning and running regression tests.
Affected datasets (arxiv, products, papers100M)
Able to download OGB MAG

**Comment by classicsong** [comment]
Can you provide steps to reproduce this error?

**Comment by zhjwy9343** [comment]
Problem solved after OGB update its version to 1.3.6 in April 7th. So they may change the raw data but forget to update the library.

**Comment by prateekdesai04** [comment]
Taking up the issue, will put a PR to explicitly mention the version (1.3.6) while installation
