### ISSUE TITLE
[Bug] Large integer features will lost precision after graph construction

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#704]
## Phenomena:

If using large integer numbers (~67M) as node features, the graph construction process will convert them as float32 and store as float32 tensor. But the float32 losses precision, and when cast the float32 back to int, it will generate duplicated integer. 

## Impact:

Users want to add original node ids as one of the node features, and use them for customized purposes. The lost of precision will cause ID duplications, hence resulting errors.

## How to reproduce

- Create a graph data with more than 60M nodes, and set integer node id as one of the node features. 
- Run gconstruction.
- In the partition folder, e.g., part0, read in the `node_feat.dgl` file with `dgl.data.util.load_tensors`.
- Extract the node feature with node ids, compare the feature shape against its unique values shape.
- The two shapes are different.
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/graphstorm/issues/706
- [ ] Fix for GConstruct
```

**Comment by classicsong** [comment]
Can we close this issue? @zhjwy9343
