### ISSUE TITLE
[Change Request] Set default values to GraphStorm's `gs.initialize()` function

### ISSUE THREAD

**Issue by zhjwy9343** [awslabs/graphstorm#754]
1. For users to initialize GraphStorm standalone environment more easier, need to set default argument value for initialize() method, i.e., `ip_config=None`, `backend='gloo'`, `device='cpu'`, and `log_level='info'`.

2. In order to facilitate convert code written in APIs to run with CLI interface, the GraphStorm need to provide `gs.get_device()` method for device setup internally in other classes, e.g., DataLoaders, Trainers, and Inferrers, without users' input.

Sample code
```
import graphstorm as gs
gs.initialize()
```

**Comment by classicsong** [comment]
To Note: log_level is not set by `gs.initialize`

**Comment by zhjwy9343** [comment]
How about device? Can gs.initalize() set up device?
