### ISSUE TITLE
DGL edge_split returns None when there's single edge of an etype

### ISSUE THREAD

**Issue by haozhouamzn** [awslabs/graphstorm#773]
I got following error using graphstorm
```
Traceback (most recent call last):
  File "/graphstorm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 254, in <module>
    main(gs_args)
  File "/graphstorm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 106, in main
    train_data = GSgnnLPTrainData(config.graph_name,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 641, in __init__
    super(GSgnnLPTrainData, self).__init__(graph_name, part_config,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 520, in __init__
    super(GSgnnEdgeTrainData, self).__init__(graph_name, part_config, label_field,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 398, in __init__
    super(GSgnnEdgeData, self).__init__(graph_name, part_config,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 219, in __init__
    self.prepare_data(self._g)
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 565, in prepare_data
    assert train_idx is not None, "There is no training data."
```

This trace back to following code block in [dataset.py](https://github.com/awslabs/graphstorm/blob/f042050424ff157a0c42454f0975b223adaf149a/python/graphstorm/dataloading/dataset.py#L557-L559)
```
        for canonical_etype in self.train_etypes:
            if 'train_mask' in g.edges[canonical_etype].data:
                train_idx = dgl.distributed.edge_split(
                    g.edges[canonical_etype].data['train_mask'],
                    pb, etype=canonical_etype, force_even=True)
            else:
                # If there are no training masks, we assume all edges can be used for training.
                # Therefore, we use a more memory efficient way to split the edge list.
                # TODO(zhengda) we need to split the edges properly to increase the data locality.
                train_idx = split_full_edge_list(g, canonical_etype, get_rank())
            assert train_idx is not None, "There is no training data."
            num_train += len(train_idx)
            train_idxs[canonical_etype] = train_idx
```

The error seems because there's a single edge of this `canonical_etype`, that is `len(g.edges[canonical_etype].data['train_mask'])==1`. As a result, `edge_split` returns None.

**Comment by classicsong** [comment]
Can you exclude this edge type from training target? You can use train-etype and eval-etype to specify the training and evaluation etype: https://graphstorm.readthedocs.io/en/latest/configuration/configuration-run.html#link-prediction-task

**Comment by zhjwy9343** [comment]
@classicsong I think the key concern here is about whether return a None is a good indicator to users.

Because return None will cause an error and the error message is "There is no training data.", users will get confused. In addition, only one node/edge is still a valid setting if users just want to run a small graph, while large graphs could have more nodes/edges.

Therefore, in terms of a single node/edge, GraphStorm might come up with a warning, but still can proceed to train without validation/test operation.
