### ISSUE TITLE
[Documentation] Add doc about saving configuration files in gconstruct and gsprocessing.

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#796]
Add doc about saving configuration files when processing graph input data (e.g. --output-conf-file). The saved configuration file will record how data are transformed (numerical features, categorical features, etc.).

For example:
When constructing a graph for training, we can save the configuration file recording the data transformation information by adding `--output-conf-file data_transform_new.conf`
```
python3 -m graphstorm.gconstruct.construct_graph --conf-file data_transform.conf --num-processes 2 --output-dir /tmp/test_out --graph-name test --output-format DGL --output-conf-file data_transform_new.conf
```

Then during inference, we can load the `data_transform_new.conf` for creating inference graphs.

**Comment by zhjwy9343** [comment]
A better user experience would be automatically save the configuration file. If users specify the `--output-conf-file`, save the data transformation configuration file to the given location. If not, use the default `--output-dir` and save the file with name `data_transform_new.json`.
