### ISSUE TITLE
Print warnings or error out when invalid arguments are passed

### ISSUE THREAD

**Issue by thvasilo** [awslabs/graphstorm#799]
With the number of arguments that we parse, it's likely that an arg can be misspelled.

e.g. I ran into the case where I was trying to pass `--save-embeds-path` instead of `save-embed-path` which led to my job hanging without an obvious reason.

When unknown arguments are passed to the launch scripts, we should be at least print out a warning, or error out the job (as it will likely lead to something the user did not intend).

More context:

What's happened is that the yaml file had a value for the path, which I tried to override through the CLI.

But the misspelled CLI arg was just ignored and it tried to use the one from the yaml.

**Comment by classicsong** [comment]
Print out a warning.
We need to support customized args.

**Comment by thvasilo** [comment]
Just encountered this with a user launching a SageMaker job. They provided `--instance_type` instead of `--instance-type` to the launch script, so the job was being launched with the default instance type (`ml.g4dn.12xlarge`)
