### ISSUE TITLE
Hyperparameter Optimization with GraphStorm

### ISSUE THREAD

**Issue by dombrowsky** [awslabs/graphstorm#801]
I am currently developing a model to classify a large transaction graph and want to test different graph architectures. For this purpose I want perform hyperparameter optimization for the model training, to correctly determine the real predictive power in the graph structures. 
However, I was not able to find any information on how to perform hyperparameter optimization (with SageMaker) with any GraphStorm algorithm, besides using the GraphStorm python classes with SageMaker or using a bash script to apply grid search over the CLI. 

Is there any "canonical" way or best practice on how to perfrom hyperparameter optimization with GraphStorm, preferably with Sagemaker?

Thanks for any ideas or replies.

**Comment by classicsong** [comment]
You can use the HPO capability of SageMaker to do hyperparameter search by defining the hyperparameters you want to search. Please refer to SageMaker team or doc for more details: https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning-how-it-works.html

**Comment by dombrowsky** [comment]
Thanks for your quick reply!
I am not quite sure how to define the hyperparameter to search. All I can see from the documentation is that you can optimize an estimator in a SageMaker Notebook, but that would bypass graphstorm almost completely. I would need to use the graphstorm build-in python classes to perform HPO this way or am I missing something?

**Comment by classicsong** [comment]
You can take a look of this page: https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning-ex-tuning-job.html
