### ISSUE TITLE
[GSProcessing] Custom Data Split disorder

### ISSUE THREAD

**Issue by jalencato** [awslabs/graphstorm#976]
If we store our custom split generated masks in multiple files, it will cause the final generated graph in a disorder. A temporary fix can be used to restrict it to 1. But we can try to optimize it for better scalability issue.

**Comment by datarsingh007** [comment]
Concatenate Masks: Combine all masks into a single file before generating the graph.
Indexing: Use a metadata file to maintain the order of masks stored in separate files.
Sequential Naming: Save masks with sequential filenames (e.g., mask_001, mask_002) to ensure correct processing order.
Merge After Parallel Processing: Generate masks in parallel, then reorder them using sequence numbers before merging.
Central Controller: Implement a centralized system to manage mask generation and order.

**Comment by jalencato** [comment]
Close the issue as we have already solved this via PR: https://github.com/awslabs/graphstorm/pull/1039
