### ISSUE TITLE
[RFC] Change multi-task UX to make providing mask names in GConstruct/train YAML optional

### ISSUE THREAD

**Issue by thvasilo** [awslabs/graphstorm#997]
When training muli-task jobs, we need to have one train/val/test mask per label.
Right now we require from the users to provide the names of the multi-task mask columns both in the GConstruct config and the train yaml. In this RFC we propose that those can be (optionally) automatically determined so we can reduce the burden on our users.

Current state

Currently, for a multi-task GConstruct and GSF train job, the user need to provide `"mask_field_names"` for each label participating in the task, both in the GConstruct and in the GSF yaml file:

GConstruct

```
"labels": [
                {
                    "label_col": "label_class",
                    "task_type": "classification",
                    "split_pct":    [0.8, 0.1, 0.1],
                    "mask_field_names": ["train_mask_class",
                                         "val_mask_class",
                                         "test_mask_class"]
                }
            ]
```

YAML

```
multi_task_learning:
        - node_classification:
            target_ntype: "paper"
            label_field: "label_class"
            mask_fields:
                - "train_mask_class"
                - "val_mask_class"
                - "test_mask_class"
            num_classes: 10
            task_weight: 1.0
```

This creates additional friction in the form of more verbose config files, and is a potential source of error as there’s no mechanism enforcing that the mask names remain the same between the graph construction step and the training step. We propose then that we determine these mask names ourselves, to remove this requirement from the user.

For every label in GConstrctuct/GSProcessing we already require the user to provide the label column. We can then simply append this to the name of the mask being produced, e.g. if `"label_col": "label_class"`, the produced masks would be `"[train_mask_label_class, val_mask_label_class, test_mask_label_class]"`
For link prediction we can simply append `lp` to each mask name.

Similarly, in the train yaml we already require `label_field: "label_class"`  so based on this information and the above we can derive the mask names from the yaml itself, that is we can assume the graph construction step has created masks named `"[train_mask_label_class, val_mask_label_class, test_mask_label_class]".`

This way we essentially remove the requirement that the user provides custom mask names for each task. We can maintain support for it optionally if they want to have specific mask names for some reason.

One potential complication is regarding the default behavior when the user is preparing data for a multi-task learning job, but there's only one label being used per node/edge type.

When this happens, we need to be able to tell whether the user is preparing a multi-task job by reading the entire config and figuring out if more than one label is defined. 

If make that assumption, we can create masks named `["train_mask``<label_col>", "val_mask_<label_col>", "test_mask_<label_col>"]` even when there’s only one label for a node/edge type, allowing us to maintain this assumption downstream during training. Otherwise if we only appended the label col when there’s more than one label in one node/edge type, we wouldn’t be able to rely on that assumption downstream during training.

In the end the decision process for how to name masks during graph construction will be as follows:

1. Does the graph construction config define more than one label?
    1. If yes, we assume the downstream task is MT training. All masks created will have the label column name appended.
    2. If not, we produce the mask names as usual, `"[train_mask, val_mask, test_mask]"`

The above workflow will remove one (likely unused) ability of GSProcessing currently, that allows us to process multiple labels in one job, with the intention running separate single-task jobs on each. I don’t know of any customers that have used this capability though.

**Comment by classicsong** [comment]
How to handle the following cases with the auto-mask strategy:
1. A user may want to build a graph that can be used by multiple different training tasks. He/she can use it for a link prediction task or use it for a node classification task. The default mask generation strategy may fail.
2. In a multitask setting, two node classification tasks share the same train/valid/test mask but different labels.

**Comment by thvasilo** [comment]
After internal discussion we decide to keep the current UX for now and re-visit at a later point depending on customer feedback.
